const CreateUserRouter = require('../../presentation/user/create-user-router')
const UpdateUserRouter = require('../../presentation/user/update-user-router')
const ListUserRouter = require('../../presentation/user/list-users-router')
const FindUserRouter = require('../../presentation/user/find-user-router')
const AuthUserRouter = require('../../presentation/user/auth-user-router')
const authMiddleware = require("../middlewares/auth-middleware")
const { adapt } = require('../middlewares/express-router-adapter')
const { validate } = require('../middlewares/express-middleware-adapter')
module.exports = router => {
    router.post('/user', validate(authMiddleware), adapt(CreateUserRouter))
    router.get('/users', validate(authMiddleware), adapt(ListUserRouter))
    router.get('/user/:id', validate(authMiddleware), adapt(FindUserRouter))
    router.put('/user/:id', validate(authMiddleware), adapt(UpdateUserRouter))
    router.post('/auth', adapt(AuthUserRouter))
}